version: 2
jobs:
  build:
    docker:
      - image: choib24/ubuntu-python3-node8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3.6 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  test:
    docker:
      - image: choib24/ubuntu-python3-node8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3.6 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name : run tests
          command : |
            npm test

  deploy-dev:
    docker:
      - image: choib24/ubuntu-python3-node8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3.6 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            npm install

      - run:
          name : deploy to development stage
          command : |
            npx sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
            npx sls deploy --stage dev --verbose

  deploy-prod:
    docker:
      - image: choib24/ubuntu-python3-node8

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3.6 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            npm install

      - run:
          name : deploy to development stage
          command : |
            npx sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
            npx sls deploy --stage prod --verbose

workflows:
  version: 2
  deployment-process:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-dev:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
                - develop
      - hold:
          type: approval
          requires:
           - build
           - test
           - deploy-dev
      - deploy-prod:
          requires:
            - build
            - test
            - deploy-dev
          filters:
            branches:
              only: master
