version: 2

jobs:
  build:
    docker:
      - image: choib24/ubuntu-python3-node8

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -r requirements.txt
            npm install

      - run:
          name: run unit tests
          command: |
            . venv/bin/activate
            python -m unittest tests/**/*.py
  
  deploy-dev:
    docker:
      - image: choib24/ubuntu-python3-node8

    steps:
      - checkout
    
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -r requirements.txt
            npm install

      - run:
          name: deploy to development stage
          command: |
            . venv/bin/activate
            npx sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --overwrite
            python deploy.py dev

  deploy-prod:
    docker:
      - image: choib24/ubuntu-python3-node8

    steps:
      - checkout
    
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install -r requirements.txt
            npm install
            
      - run:
          name: deploy to production stage
          command: |
            . venv/bin/activate
            npx sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --overwrite
            python deploy.py prod

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: develop
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
              - hold
          filters:
            branches:
              only: master